--CONSULTA QUE TENIA PA CRUZAR REVER Y DESCUENTOS LA COMPLETA
WITH  

REVERSIONES AS(
SELECT DISTINCT TIQUETE_ID, CONTRATO as ContratoR,FECHA_APERTURA as FechaRever
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_TIQUETES_SERVICIO_2021-01_A_2021-11_D`
WHERE CLASE IS NOT NULL AND MOTIVO IS NOT NULL AND TIQUETE_ID IS NOT NULL
AND SUBAREA <> "0 A 30 DIAS" AND SUBAREA <> "30 A 60 DIAS" AND SUBAREA <> "60 A 90 DIAS" 
AND SUBAREA <> "90 A 120 DIAS" AND SUBAREA <> "120 A 150 DIAS" AND SUBAREA <> "150 A 180 DIAS" 
AND SUBAREA <> "MAS DE 180" AND MOTIVO <> "LLAMADA  CONSULTA DESINSTALACION"
AND ESTADO <> "ANULADA" AND MOTIVO = "REVERSION AUTOMATICA"
GROUP BY TIQUETE_ID,CONTRATO,FechaRever),

DESCUENTOSINFINITOS AS (
SELECT  DISTINCT Numero_Tiquete, Fecha_Tiquete as FechaDescuento
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_DESCUENTOS_OVAL_ADJ_T` 
WHERE EXTRACT (YEAR FROM Fecha_Fin_Regalia)=1900
GROUP BY Numero_Tiquete, Fecha_Tiquete),

CRUCE AS(
SELECT DISTINCT r.TIQUETE_ID, d.Numero_Tiquete, r.ContratoR, r.FechaRever, d.FechaDescuento
FROM REVERSIONES r INNER JOIN DESCUENTOSINFINITOS d ON r.TIQUETE_ID=d.Numero_Tiquete
WHERE r.FechaRever>d.FechaDescuento
GROUP BY r.TIQUETE_ID, d.Numero_Tiquete, r.ContratoR, r.FechaRever, d.FechaDescuento
),

CHURNERS AS(SELECT DISTINCT h.NOMBRE_CONTRATO, h.FECHA_FINALIZACION as FechaChurn
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_ORDENES_SERVICIO_2021-01_A_2021-11_D` h 
INNER JOIN CRUCE c on c.ContratoR = h.NOMBRE_CONTRATO
WHERE h.TIPO_ORDEN = "DESINSTALACION" AND h.ESTADO = "FINALIZADA" 
AND h.FECHA_FINALIZACION IS NOT NULL AND h.FECHA_APERTURA IS NOT NULL
AND h.FECHA_FINALIZACION > c.FechaRever  AND DATE_DIFF (h.FECHA_FINALIZACION, c.FechaRever, DAY) <= 60
GROUP BY h.NOMBRE_CONTRATO, h.FECHA_FINALIZACION),

CHURNFLAGRESULT AS(
SELECT DISTINCT c.TIQUETE_ID, c.Numero_Tiquete, c.ContratoR, c.FechaRever, c.FechaDescuento,h.FechaChurn,
CASE WHEN h.FechaChurn IS NOT NULL THEN "Churner"
WHEN h.FechaChurn IS NULL THEN "NonChurner" end as ChurnFlag
FROM CRUCE c LEFT JOIN CHURNERS h ON c.ContratoR = h.NOMBRE_CONTRATO
GROUP BY c.TIQUETE_ID, c.Numero_Tiquete, c.ContratoR, c.FechaRever, c.FechaDescuento,h.FechaChurn)

SELECT DISTINCT t.TIQUETE_ID, t.Numero_Tiquete, t.ContratoR, t.FechaRever, t.FechaDescuento,t.FechaChurn
FROM CHURNFLAGRESULT t



