WITH  

REVERSIONES AS(
SELECT DISTINCT CONTRATO, FECHA_APERTURA as FechaRever
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_TIQUETES_SERVICIO_2021-01_A_2021-11_D`
WHERE CLASE IS NOT NULL AND MOTIVO IS NOT NULL AND CONTRATO IS NOT NULL
AND SUBAREA <> "0 A 30 DIAS" AND SUBAREA <> "30 A 60 DIAS" AND SUBAREA <> "60 A 90 DIAS" 
AND SUBAREA <> "90 A 120 DIAS" AND SUBAREA <> "120 A 150 DIAS" AND SUBAREA <> "150 A 180 DIAS" 
AND SUBAREA <> "MAS DE 180" AND MOTIVO <> "LLAMADA  CONSULTA DESINSTALACION"
AND ESTADO <> "ANULADA" AND MOTIVO = "REVERSION AUTOMATICA"
GROUP BY CONTRATO,FechaRever)

SELECT COUNT(DISTINCT CONTRATO), EXTRACT (month from FechaRever) as mes
FROM REVERSIONES
GROUP BY mes ORDER BY mes
