/*Muy pocos tiquetes que cruzan-no sirve*/
WITH

DESCUENTOS AS (
SELECT  DISTINCT Numero_Tiquete, Fecha_Fin_Regalia as FechaFinDescuento
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_DESCUENTOS_OVAL_ADJ_T` 
WHERE EXTRACT (YEAR FROM Fecha_Fin_Regalia)<>1900
GROUP BY Numero_Tiquete, Fecha_Fin_Regalia),

TIQUETESCONDESCUENTOS AS (
SELECT DISTINCT TIQUETE_ID, CONTRATO, d.FechaFinDescuento, d.Numero_Tiquete
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_TIQUETES_SERVICIO_2021-01_A_2021-11_D` t
INNER JOIN DESCUENTOS d ON t.TIQUETE_ID=d.Numero_Tiquete
GROUP BY TIQUETE_ID, CONTRATO, d.FechaFinDescuento, d.Numero_Tiquete
),

CHURNERS AS(
SELECT DISTINCT NOMBRE_CONTRATO, FECHA_FINALIZACION as FechaChurn
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_ORDENES_SERVICIO_2021-01_A_2021-11_D` c
INNER JOIN TIQUETESCONDESCUENTOS t ON c.NOMBRE_CONTRATO=t.CONTRATO
WHERE TIPO_ORDEN = "DESINSTALACION" AND ESTADO = "FINALIZADA" 
AND FECHA_FINALIZACION IS NOT NULL AND FECHA_APERTURA IS NOT NULL
AND FECHA_FINALIZACION > t.FechaFinDescuento  AND DATE_DIFF (FECHA_FINALIZACION, t.FechaFinDescuento, DAY) <= 60
GROUP BY NOMBRE_CONTRATO, FECHA_FINALIZACION),

CHURNFLAGRESULT AS(
SELECT DISTINCT t.Numero_Tiquete,t.FechaFinDescuento, c.FechaChurn,
CASE WHEN c.FechaChurn IS NOT NULL THEN "Churner"
WHEN c.FechaChurn IS NULL THEN "NonChurner" end as ChurnFlag
FROM TIQUETESCONDESCUENTOS t LEFT JOIN CHURNERS c ON c.NOMBRE_CONTRATO=t.CONTRATO
GROUP BY t.Numero_Tiquete, t.FechaFinDescuento, c.FechaChurn
)

SELECT COUNT(DISTINCT f.Numero_Tiquete), EXTRACT(MONTH FROM f.FechaFinDescuento) as Mes
FROM CHURNFLAGRESULT f
--WHERE ChurnFlag="Churner"
GROUP BY Mes ORDER BY Mes
