WITH  

REVERSIONES AS(
SELECT DISTINCT CONTRATO, FECHA_APERTURA as FechaRever
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_TIQUETES_SERVICIO_2021-01_A_2021-11_D`
WHERE CLASE IS NOT NULL AND MOTIVO IS NOT NULL AND CONTRATO IS NOT NULL
AND SUBAREA <> "0 A 30 DIAS" AND SUBAREA <> "30 A 60 DIAS" AND SUBAREA <> "60 A 90 DIAS" 
AND SUBAREA <> "90 A 120 DIAS" AND SUBAREA <> "120 A 150 DIAS" AND SUBAREA <> "150 A 180 DIAS" 
AND SUBAREA <> "MAS DE 180" AND MOTIVO <> "LLAMADA  CONSULTA DESINSTALACION"
AND ESTADO <> "ANULADA" AND MOTIVO = "REVERSION AUTOMATICA"
GROUP BY CONTRATO,FechaRever),

FACTURACION AS (
SELECT DISTINCT CONTRATO, FECHA_APERTURA AS FechaFact
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_TIQUETES_SERVICIO_2021-01_A_2021-11_D` 
WHERE 
CLASE IS NOT NULL AND MOTIVO IS NOT NULL AND CONTRATO IS NOT NULL AND FECHA_APERTURA IS NOT NULL 
AND SUBAREA <> "0 A 30 DIAS" AND SUBAREA <> "30 A 60 DIAS" AND SUBAREA <> "60 A 90 DIAS" 
AND SUBAREA <> "90 A 120 DIAS" AND SUBAREA <> "120 A 150 DIAS" AND SUBAREA <> "150 A 180 DIAS" 
AND SUBAREA <> "MAS DE 180" AND ESTADO <> "ANULADA"
AND MOTIVO="CONSULTAS DE FACTURACION O COBRO"
GROUP BY CONTRATO, FechaFact),

CRUCE AS (
SELECT DISTINCT r.CONTRATO, f.CONTRATO as contratos, f.FechaFact, r.FechaRever 
FROM REVERSIONES r INNER JOIN FACTURACION f ON r.CONTRATO=f.CONTRATO
WHERE DATE_DIFF(f.FechaFact,r.FechaRever,DAY)<=60
AND f.FechaFact>r.FechaRever
GROUP BY r.CONTRATO,f.CONTRATO, f.FechaFact, r.FechaRever
),

CHURNERS AS(SELECT DISTINCT h.NOMBRE_CONTRATO, h.FECHA_APERTURA, h.FECHA_FINALIZACION as FechaChurn
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_ORDENES_SERVICIO_2021-01_A_2021-11_D` h 
INNER JOIN CRUCE c on c.Contratos = h.NOMBRE_CONTRATO
WHERE h.TIPO_ORDEN = "DESINSTALACION" AND h.ESTADO = "FINALIZADA" 
AND h.FECHA_FINALIZACION IS NOT NULL AND h.FECHA_APERTURA IS NOT NULL
AND h.FECHA_FINALIZACION > c.FechaFact  AND DATE_DIFF ( h.FECHA_FINALIZACION, c.FechaFact, DAY) <= 60
GROUP BY h.NOMBRE_CONTRATO, h.FECHA_APERTURA, h.FECHA_FINALIZACION),

CHURNFLAGRESULT AS(
SELECT DISTINCT c.Contratos, c.FechaFact,c.FechaRever,h.FechaChurn ,
CASE WHEN h.FechaChurn IS NOT NULL THEN "Churner"
WHEN h.FechaChurn IS NULL THEN "NonChurner" end as ChurnFlag
FROM CRUCE c 
LEFT JOIN CHURNERS h ON c.Contratos = h.NOMBRE_CONTRATO
--WHERE h.FechaChurn > c.FechaFact  AND DATE_DIFF ( h.FechaChurn, c.FechaFact, DAY) <= 60
GROUP BY c.contratos, c.FechaFact,c.FechaRever, ChurnFlag, h.FechaChurn)

SELECT 
--DISTINCT t.Contratos, t.FechaAltas,t.FechaFact,t.FechaChurn 
COUNT (DISTINCT t.Contratos) as Registros, EXTRACT(MONTH FROM t.FechaRever) as Mes 
FROM CHURNFLAGRESULT t
WHERE ChurnFlag = "Churner"
--WHERE ChurnFlag = "NonChurner"
GROUP BY Mes ORDER BY Mes

